/* Chia dữ liệu và tiền xử lý: so sánh scaler đúng với rò rỉ dữ liệu. */
(function(){'use strict';const W=typeof module!=='undefined'&&module.exports?require('../learning/workflows.js'):window.LearningWorkflows;
  const data=[1,2,3,4,5,6,7,8,9,100];
  const lesson=W.lesson({id:'ai-data',course:'ai',title:'Dữ liệu, tiền xử lý và rò rỉ',lead:'Chia train/validation/test rồi học phép chuẩn hóa chỉ trên train; xem một điểm ngoại lệ làm lệch scaler khi dùng toàn bộ dữ liệu.',
    experiment:{defaults:{trainRatio:0.6,validationRatio:0.2,seed:3,fitOn:'train'},controls:[{key:'trainRatio',label:'Tỷ lệ train (tập huấn luyện)',type:'number',min:0.1,max:0.8,step:0.1},{key:'validationRatio',label:'Tỷ lệ validation (tập lựa chọn)',type:'number',min:0.1,max:0.8,step:0.1},{key:'seed',label:'Seed (giá trị khởi tạo ngẫu nhiên)',type:'number',min:0,step:1},{key:'fitOn',label:'Dữ liệu dùng để học scaler',type:'select',options:[{value:'train',label:'Chỉ train — đúng quy trình'},{value:'all',label:'Toàn bộ — minh họa rò rỉ'}]}],run:i=>{
      if(!['train','all'].includes(i.fitOn))throw new Error('Chọn phạm vi học scaler.');
      const sets=W.split(data,i.trainRatio,i.validationRatio,i.seed),scaler=W.fitScaler(i.fitOn==='train'?sets.train:data);
      return {seed:i.seed,sets,counts:{train:sets.train.length,validation:sets.validation.length,test:sets.test.length},scaler,normalizedValidation:W.transform(sets.validation,scaler),leakage:i.fitOn==='all',note:'Dữ liệu mẫu chỉ có một đặc trưng; đây là phép tính chuẩn hóa, không huấn luyện mô hình.'};
    }},tasks:[
      {title:'Chia đúng 6/2/2',desc:'Dùng seed 3, tỷ lệ 0.6/0.2 và scaler chỉ train.',hint:'Để mặc định rồi bấm Chạy.',accept:r=>r.seed===3&&!r.leakage&&r.counts&&r.counts.train===6&&r.counts.validation===2},
      {title:'So sánh một cách chia khác',desc:'Đổi seed để quan sát mẫu từng tập và mean train.',hint:'Đổi seed thành 4, giữ scaler chỉ train.',accept:r=>r.seed===4&&!r.leakage&&!!r.scaler},
      {title:'Quan sát rò rỉ',desc:'Cho scaler học toàn bộ dữ liệu rồi xem cảnh báo.',hint:'Đặt seed 3 và chọn Toàn bộ.',accept:r=>r.leakage===true},
      {title:'Bảo vệ tập test',desc:'Thử tỷ lệ khiến tổng train và validation vượt 1.',hint:'Train 0.9 và validation 0.2.',accept:r=>r.errorCode==='NO_TEST_SPLIT'}
    ],quiz:[
      {q:'Tập nào dùng để học trọng số?',options:['Train','Test','Cả ba'],answer:0,explain:'Train là dữ liệu huấn luyện. Test cần được giữ ngoài mọi quyết định chọn mô hình.'},
      {q:'Mean và độ lệch chuẩn của scaler nên học ở đâu?',options:['Toàn bộ dữ liệu','Chỉ train','Chỉ test'],answer:1,explain:'Học thống kê trên train rồi áp dụng nguyên trạng cho validation và test để tránh rò rỉ.'},
      {q:'Validation dùng làm gì?',options:['Chọn cấu hình mô hình','Bảo đảm kết quả tuyệt đối','Thay train'],answer:0,explain:'Validation giúp chọn bậc, ngưỡng hoặc cấu hình; test được dùng cho đánh giá cuối.'},
      {q:'Dữ liệu chuỗi thời gian nên chia thế nào?',options:['Luôn trộn ngẫu nhiên','Giữ thứ tự thời gian, học quá khứ dự đoán tương lai','Theo tên file'],answer:1,explain:'Trộn ngẫu nhiên có thể đưa thông tin tương lai vào tập huấn luyện và làm kết quả quá lạc quan.'},
      {q:'Một khách hàng có nhiều bản ghi, cần lưu ý gì?',options:['Cho vào mọi tập','Chia theo nhóm khách hàng khi đánh giá khách hàng mới','Xóa hết nhãn'],answer:1,explain:'Bản ghi cùng người trong cả train và test có thể tiết lộ thông tin và sai mục tiêu đánh giá.'},
      {q:'Seed cố định bảo đảm điều gì?',options:['Lặp lại cùng cách chia','Mô hình luôn đúng','Hết mất cân bằng lớp'],answer:0,explain:'Seed giúp tái lập thí nghiệm. Nó không bảo đảm dữ liệu đại diện hay chất lượng mô hình.'}
    ],study:{sections:[{title:'Quy trình trước khi huấn luyện',html:'<p>Xác định nhãn và đơn vị cần dự đoán, kiểm tra dữ liệu trùng/thiếu rồi tách train (huấn luyện), validation (lựa chọn) và test (kiểm tra cuối). Phân loại mất cân bằng nên cân nhắc chia phân tầng theo nhãn; dữ liệu theo người cần chia nhóm, dữ liệu theo thời gian cần giữ thứ tự.</p>'},{title:'Chuẩn hóa và rò rỉ',html:'<p>StandardScaler biến đổi z = (x − mean_train)/std_train. Ví dụ train [2,4] có mean 3, độ lệch chuẩn 1; giá trị mới 100 thành 97. Không học lại mean trên validation/test. Cột hằng có độ lệch chuẩn 0 dùng hệ số 1 để tránh chia cho 0. Imputation (điền giá trị thiếu), chọn đặc trưng và scaler cũng phải fit trong từng fold (lượt chia) khi kiểm định chéo. Pipeline giúp giữ quy tắc này.</p>'}],practice:{title:'Thực hành: nhật ký chia dữ liệu',goal:'Nhận biết một quy trình tái lập và điểm rò rỉ.',steps:['Chạy cấu hình mặc định, ghi mẫu và mean train.','Đổi seed 4 rồi ghi sự khác nhau.','Cho scaler học toàn bộ, so sánh mean và cảnh báo.','Ngoài trình duyệt, dùng train_test_split và Pipeline theo nguồn chính thức; giữ test riêng.'],expected:'Ba tập không trùng mẫu; scaler đúng chỉ phụ thuộc train. Tỷ lệ sai bị từ chối.',troubleshooting:['Dữ liệu ít khiến một tập rỗng: tăng số mẫu hoặc sửa tỷ lệ.','Kết quả quá cao: kiểm tra bản ghi trùng, nhãn xuất hiện trong đặc trưng và bước fit trước khi chia.']},references:[{title:'scikit-learn: tránh rò rỉ',url:'https://scikit-learn.org/stable/common_pitfalls.html',topic:'Rò rỉ dữ liệu',note:'Đọc quy tắc split trước fit và cách dùng Pipeline.',checked:'07/10/2026'},{title:'scikit-learn: tiền xử lý',url:'https://scikit-learn.org/stable/modules/preprocessing.html',topic:'Chuẩn hóa',note:'Đọc StandardScaler, cột hằng và lựa chọn phép biến đổi.',checked:'07/10/2026'}]}
  });lesson.study.practice.download='examples/ml/workflow.py';lesson.study.sections.push({title:'Thực hành trên máy',html:'<p><a href="docs/tutorials/ml.html">Hướng dẫn chia tập và hồi quy trên máy</a>: điều kiện, lệnh chạy, kết quả và giới hạn.</p>'});if(typeof module!=='undefined'&&module.exports)module.exports=lesson;else App.register(lesson);
})();
