/* Nền tảng mô hình ngôn ngữ và ngân sách ngữ cảnh. */
(function(){
  'use strict';
  const M=typeof module!=='undefined'&&module.exports?require('../../learning/experiments.js'):window.LearningMath;
  const lesson=M.lesson({id:'genai-foundations',title:'Nền tảng AI tạo sinh',lead:'Phân biệt học và suy luận, chọn tác vụ phù hợp và dành chỗ cho câu trả lời trong ngữ cảnh.',
    experiment:{defaults:{limit:100,prompt:90,reserve:20},controls:[{key:'limit',label:'Giới hạn ngữ cảnh (token minh họa)',type:'number',min:1,step:1},{key:'prompt',label:'Token của câu lệnh và tài liệu',type:'number',min:0,step:1},{key:'reserve',label:'Token dành cho đầu ra',type:'number',min:0,step:1}],run:i=>({...M.contextBudget(i.limit,i.prompt,i.reserve),message:i.prompt+i.reserve>i.limit?'Vượt ngữ cảnh: rút ngắn tài liệu hoặc giảm đầu ra.':'Ngân sách đủ cho đầu vào và đầu ra.'})},
    tasks:[{title:'Phát hiện tràn ngữ cảnh',desc:'Chạy 100 / 90 / 20 và đọc phần vượt giới hạn.',hint:'Giới hạn 100, đầu vào 90, dự trữ 20.',accept:r=>r.fits===false&&r.remaining===-10},{title:'Dành chỗ cho đầu ra',desc:'Giảm đầu vào để còn 20 token sau dự trữ.',hint:'100 / 60 / 20.',accept:r=>r.fits===true&&r.remaining===20},{title:'Dùng hết ngân sách',desc:'Chạy một cấu hình vừa đúng giới hạn.',hint:'100 / 60 / 40.',accept:r=>r.fits===true&&r.remaining===0},{title:'Tăng ngữ cảnh có kiểm soát',desc:'Tạo cấu hình còn 70 token và so sánh với lần tràn.',hint:'200 / 100 / 30.',accept:r=>r.fits===true&&r.remaining===70}],
    quiz:[
      {q:'Mô hình ngôn ngữ lớn thường học mục tiêu gì khi huấn luyện trước?',options:['Dự đoán token tiếp theo','Tra cứu Internet ở mọi bước','Lưu tất cả trang web nguyên bản'],answer:0,explain:'Token là đơn vị văn bản của mô hình. Học xác suất token tiếp theo tạo nền tảng cho nhiều tác vụ.'},
      {q:'Suy luận khác huấn luyện ở điểm nào?',options:['Luôn cập nhật trọng số','Dùng trọng số đã học để tạo đầu ra','Không cần đầu vào'],answer:1,explain:'Suy luận thông thường giữ nguyên trọng số. Việc cập nhật trọng số thuộc quá trình huấn luyện hoặc điều chỉnh.'},
      {q:'Giới hạn 100, đầu vào 80, dự trữ đầu ra 30 có vừa không?',options:['Có','Không, tổng là 110','Chỉ phụ thuộc đầu vào'],answer:1,explain:'Cần tính cả đầu vào, lịch sử, chỉ dẫn và đầu ra theo quy tắc ngữ cảnh của mô hình.'},
      {q:'Câu trả lời rất tự tin chứng minh điều gì?',options:['Dữ kiện đúng','Có nguồn chính thức','Chưa chứng minh tính đúng'],answer:2,explain:'Văn bản trôi chảy vẫn có thể chứa thông tin sai. Kiểm tra với tài liệu hoặc công cụ độc lập.'},
      {q:'Tác vụ nào cần nguồn cập nhật nhất?',options:['Viết lại câu cho dễ đọc','Tra chính sách hoàn tiền đang áp dụng','Đổi cách diễn đạt'],answer:1,explain:'Chính sách có thể thay đổi. Dùng tài liệu được quản lý, ghi ngày áp dụng và nguồn.'},
      {q:'Tách theo khoảng trắng trong bài có phải tokenizer thật?',options:['Có cho mọi mô hình','Không, chỉ minh họa','Có riêng tiếng Việt'],answer:1,explain:'Bộ tách token thật phụ thuộc mô hình; một từ có thể thành nhiều token, đặc biệt trong tiếng Việt.'}
    ],
    study:{sections:[
      {title:'Từ trí tuệ nhân tạo đến văn bản sinh ra',html:'<p>AI tạo sinh là nhóm phương pháp tạo nội dung mới dựa trên mẫu đã học: văn bản, ảnh, âm thanh hoặc mã. Mô hình ngôn ngữ lớn, gọi là LLM (Large Language Model), xử lý chuỗi token. Token có thể là một phần từ, dấu câu hoặc ký hiệu. Khi sinh văn bản, mô hình tính phân phối xác suất cho token tiếp theo, chọn một token rồi lặp lại. Phân phối phản ánh điều mô hình học được; nó không phải bằng chứng rằng một dữ kiện ngoài đời là đúng.</p><p>Huấn luyện trước học từ tập dữ liệu lớn. Điều chỉnh sau đó giúp mô hình làm theo chỉ dẫn hoặc thích nghi tác vụ. Suy luận là dùng trọng số đã học với đầu vào mới. Một cuộc trò chuyện thông thường không tự huấn luyện lại trọng số. Chỉ dẫn rõ và ví dụ có thể đổi cách trả lời trong phiên mà không thay mô hình.</p>'},
      {title:'Ví dụ thực tế: trợ lý chính sách cửa hàng',html:'<p>Khách hỏi “Có được hoàn tiền sau 10 ngày không?”. Trước hết tìm phiên bản chính sách hiện hành. Nếu tài liệu ghi 7 ngày, câu trả lời nên nêu điều kiện và dẫn nguồn. Nếu thiếu tài liệu, trợ lý cần nói chưa đủ thông tin thay vì đoán. Với tác vụ viết lại email, bạn có thể dùng mô hình trực tiếp rồi duyệt. Với số tiền hoàn trả, hãy tính bằng chương trình và yêu cầu người dùng xác nhận trước hành động.</p><p>Quy trình: xác định tác vụ; chọn dữ liệu cần thiết; bỏ thông tin cá nhân không cần dùng; dành ngân sách đầu ra; chạy; kiểm tra nội dung và nguồn. Tách chất lượng diễn đạt khỏi tính đúng của dữ kiện. Tạo một bộ câu hỏi mẫu trước khi áp dụng cho khách hàng.</p>'},
      {title:'Ngữ cảnh và lỗi thường gặp',html:'<p>Ngữ cảnh chứa chỉ dẫn, lịch sử hội thoại, tài liệu và phần trả lời. Mô phỏng lấy giới hạn trừ đầu vào và dự trữ đầu ra. Ví dụ 100 − 90 − 20 = −10: cấu hình thiếu chỗ. Cách xử lý là tóm tắt lịch sử, chỉ lấy tài liệu liên quan hoặc giới hạn câu trả lời. Số token ở đây do bạn nhập để học nguyên lý; khi làm thật phải đo bằng tokenizer tương ứng.</p><p>Đưa toàn bộ tài liệu vào không bảo đảm câu trả lời tốt hơn: chi tiết không liên quan tăng nhiễu và chi phí. Không đánh đồng giới hạn ngữ cảnh với kiến thức đã học. Một tài liệu có trong ngữ cảnh vẫn cần được đọc đúng; kiểm thử câu trả lời với các câu hỏi có và không có bằng chứng.</p>'}
    ],practice:{title:'Thực hành: lập bảng ngân sách',goal:'Tạo bảng cho một cuộc hội thoại hỗ trợ, không cần gọi dịch vụ.',steps:['Ghi riêng token minh họa cho chỉ dẫn, lịch sử và tài liệu; cộng thành đầu vào.','Dành 20 token đầu ra và thử giới hạn 100; chạy cấu hình 90 rồi 60.','Ghi vì sao cần rút ngắn tài liệu và câu nào cần đối chiếu chính sách thật.'],expected:'90 + 20 vượt 100; 60 + 20 còn 20. Câu hỏi về chính sách cần nguồn có ngày áp dụng.',troubleshooting:'Nếu tính khác, kiểm tra đã cộng cả lịch sử và dự trữ đầu ra. Đây là ngân sách minh họa, không phải phép đo token thật.'},references:[{title:'Hugging Face: khả năng và giới hạn của mô hình ngôn ngữ',url:'https://huggingface.co/learn/llm-course/chapter1/4',topic:'LLM và giới hạn',note:'Đọc để hiểu mô hình học gì và vì sao cần đánh giá dữ kiện.',checked:'07/10/2026'},{title:'Transformers: cấu hình sinh văn bản',url:'https://huggingface.co/docs/transformers/main_classes/text_generation',topic:'Ngữ cảnh và sinh văn bản',note:'Đối chiếu tham số giới hạn token khi thực hành với mô hình thật.',checked:'07/10/2026'}]}
  });lesson.study.practice.download='docs/tutorials/genai.html';lesson.study.sections.push({title:'Thực hành trên máy',html:'<p><a href="docs/tutorials/genai.html">Thử mô hình thật trong môi trường riêng</a>: điều kiện, lệnh chạy, kết quả và giới hạn.</p>'});if(typeof module!=='undefined'&&module.exports)module.exports=lesson;else App.register(lesson);
})();
